---
title: "DATA 608 Final Project Writeup Introduction"
author: "Andrew Carson"
date: "December 13, 2018"
output:
  html_document:
      highlight: tango
      theme: united
  pdf_document: default
---

<!--# Final Project: Energy Usage-->

## Introduction

The environmental effects of global warming are having and will continue to have a negative impact on people around the world, and in particular, on the poorest and least capable of adjusting to the change through the use of resources.  In addition, the higher cost of cleaner alternative energy will be more burdensome to the poorest people and countries.  This is a serious matter of social justice.

Reducing energy usage (when the burning of fossil fuels for energy production to sustain energy consumption is contributing to global warming via CO2 emissions) is one way of combating global warming and addressing this matter of environmental and social concern.  Hence, it is important for businesses and homeowners to understand what factors increase energy usage, what might be done to reduce energy usage, and thereby reduce their contribution to global warming.

The task of this project is to visually demonstrate and understand the prominent factors that lead to increased energy usage at the local level.  To motivate this effort, I first produce visualizations that demonstrate the relationships between global energy usage, CO2 emissions, and global relative average temperatures.  Having demonstrated the strong correlations among these three, I next produce visualizations that show how home energy usage relates to various factors responsible for my home energy usage increasing and decreasing, including: local temperature, time of day, day of week, month, and (inferred) appliances/devices in use.

## Visualizations

The visualizations referred to are located on the "Global Energy Visuals" and "Home Energy Visuals" tabs in this Shiny app.

## Data Sources

The data sources are:

  * Home energy usage data from my own house from September 1st, 2017 through September 30, 2018.  After having exported from the device (reference: http://eyedro.com/how-to-export-to-excel-from-myeyedro/), the data is now stored in my GitHub repo:
    + https://github.com/anrcarson/CUNY-MSDA/tree/master/DATA608/FinalProject
  * Global yearly average temperatures:
    + https://climate.nasa.gov/vital-signs/global-temperature/
    + https://climate.nasa.gov/system/internal_resources/details/original/647_Global_Temperature_Data_File.txt
  * Global energy/fuel usage:
    + https://www.eia.gov/totalenergy/data/browser/index.php?tbl=T01.01#/?f=A&start=1949&end=2017&charted=4-6-7-14
  * Global CO2 emissions:
    + http://cdiac.ess-dive.lbl.gov/trends/emis/tre_glob_2014.html
    + https://www.epa.gov/ghgemissions/global-greenhouse-gas-emissions-data
  * Local weather history to Seattle, WA:
    + https://www.wunderground.com/history/monthly/us/wa/seattle-boeing/KBFI/date/2017-8
    
All the above data has been exported for use in the visualizations and is located here: 

  * https://github.com/anrcarson/CUNY-MSDA/tree/master/DATA608/FinalProject

## Parameters of the Data

The data sources above combine into two different data sets with the following parameters:

### Global

  * Energy Production and Consumption 
    + 	Nuclear, exports, imports, stock change/other, fuels, renewable, and totals.
    + 	Unit: Quadrillion BTU
  * CO2 Emissions 
    + 	Gas fuel, liquid fuel, solid fuel, cement production, gas flaring, per capita, and total.
    + 	Unit: million metric tons of Carbon
  * Global Temperature Change 
    + 	The change in global surface temperature relative to 1951-1980 average temperatures (mean relative temperature), Lowess smoothed mean relative temperature
    + 	Unit: degrees Celsius
  * Year

### Home

  * Calendar 
    +   Year, month, date, hour, day of the week, and day (of the month).
  * Watt Hours 
    + 	Total and average; port A, port B, and total.
    + 	Unit: Watt hours
  * Daily Temperature 
    + 	Maximum, minimum, average, difference from 65 degrees.
    + 	Unit: degrees Fahrenheit
  * Daily Dewpoint 
    + 	Maximum, minimum, average
    + 	Unit: degrees Fahrenheit
  * Humidity 
    + 	Maximum, minimum
    + 	Unit: percentage %
  * Windspeed 
    + 	Maximum, minimum
    + 	Unit: mph
  * Pressure 
    + 	Maximum, minimum
    + 	Unit: Hg
  * Precipitation 
    + 	Average
    + 	Unit: inches
    
